name: Build Development Version

# This workflow builds unsigned development versions for testing
# It doesn't require certificates and runs on every push to main/master
# For signed releases, use the "Build and Release macOS App" workflow with tags

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build app (Development)
      run: |
        xcodebuild -project MultiTimeInMenuBar.xcodeproj \
                   -scheme MultiTimeInMenuBar \
                   -configuration Release \
                   -derivedDataPath build/ \
                   build \
                   CODE_SIGN_IDENTITY="-" \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGNING_ALLOWED=NO \
                   MACOSX_DEPLOYMENT_TARGET=15.2
                   
    - name: Locate and prepare app
      run: |
        # Find the built app
        APP_PATH=$(find build -name "MultiTimeInMenuBar.app" -type d | head -1)
        echo "Found app at: $APP_PATH"
        
        # Create export directory and copy app
        mkdir -p build/export
        cp -R "$APP_PATH" build/export/
                   
    - name: Create ZIP for development
      run: |
        cd build/export
        zip -r MultiTimeInMenuBar-dev.zip MultiTimeInMenuBar.app
        mv MultiTimeInMenuBar-dev.zip ../../
        
    - name: Get version
      id: version
      run: |
        VERSION="dev-$(git rev-parse --short HEAD)"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Upload Development Build
      uses: actions/upload-artifact@v4
      with:
        name: MultiTimeInMenuBar-${{ steps.version.outputs.version }}
        path: MultiTimeInMenuBar-dev.zip 